flights/flights/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('airport/', include('flightsapp.urls'), name='flights'),
]

flights/flightsapp/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = "flightsapp"

urlpatterns = [
    path('flights/', views.flights, name='home'),
    path('login/', LoginView.as_view(template_name='flightsapp/login.html'), name='login'),
    path('new-arrival/', views.new_arrival, name='new-arrival'),
    path('new-departure/', views.new_departure, name='new-departure'),
]

flights/flightsapp/models.py
from django.db import models

# Create your models here.

class Arrival(models.Model):
    flight_no = models.CharField( max_length=6)
    time = models.TimeField()
    origin = models.CharField(max_length=45)
    remarks = models.CharField(max_length=45)
    
class Departure(models.Model):
    flight_no = models.CharField(blank=False, max_length=6)
    time = models.TimeField()
    to = models.CharField(max_length=45)
    gate = models.CharField(blank=False, max_length=2)
    remarks = models.CharField(max_length=45) 
    

flights/flightsapp/forms.py
from django import forms
from .models import Arrival, Departure

class ArrivalForm(forms.ModelForm):
    class Meta:
        model = Arrival
        fields = ['time', 'origin', 'flight_no', 'remarks']
        
        
class DepartureForm(forms.ModelForm):
    class Meta:
        model = Departure
        fields = ['time', 'to', 'flight_no', 'gate', 'remarks']

flights/flightsapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .models import Arrival, Departure
from .forms import ArrivalForm, DepartureForm
# Create your views here.

def flights(request):
    arrivals = Arrival.objects.all()
    deapertures = Departure.objects.all()
    
    return render(request, 'flightsapp/flights.html', {'arrivals':arrivals, 'deapertures':deapertures})

@login_required
def new_arrival(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ArrivalForm(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('flightsapp:new-arrival'))
        else:
            form = ArrivalForm()
        return render(request, 'flightsapp/new-arrival.html', {'form': form})

@login_required
def new_departure(request):
    if request.method == 'POST':
        form = DepartureForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('flightsapp:new-departure'))
    else:
        form = DepartureForm()
    return render(request, 'flightsapp/new-departure.html', {'form': form})

flights/flightsapp/templates/flightsapp/flights.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Flights</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'flightsapp/flights.css'%}">
<body>
    <div class="container">
    <h2>ARRIVALS </h2>
    <table>
        <thead>
          <tr>
            <th>TIME</th>
            <th>FROM</th>
            <th>FLIGHT NO.</th>
            <th>REMARKS</th>
          </tr>
        </thead>
        <tbody>
          {% for fly in arrivals %}
          <tr>
              <td>{{ fly.time }}</td>
              <td>{{ fly.origin }}</td>
              <td>{{ fly.flight_no }}</td>
              <td>{{ fly.remarks }}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
  
  <br>
  <h2>DEAPERTURES </h2>
      <table class='table2'>
        <thead>
          <tr>
            <th>TIME </th>
            <th>TO </th>
            <th>FLIGHT NO. </th>
            <th>GATE. </th>
            <th>REMARKS </th>
          </tr>
        </thead>
        <tbody>
          {% for fly in deapertures %}
          <tr>
              <td>{{ fly.time }}</td>
              <td>{{ fly.to }}</td>
              <td>{{ fly.flight_no }}</td>
              <td>{{ fly.gate }}</td>
              <td>{{ fly.remarks }}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table>
      <p ><a id='admin' href="{% url 'flightsapp:login' %}">Admin Site</a></p>
    </div>
</body>
</html>

flights/flightsapp/templates/flightsapp/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'flightsapp/generic.css'%}">
</head>
<body>
    <form class="login" method='post'>
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Entrar">
    </form>
</body>
</html>

flights/flightsapp/templates/flightsapp/new-arrival.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'flightsapp/generic.css'%}">

</head>
<body>

  <form class="new" method="post">
    <h1>New Arrival</h1>
      {% csrf_token %}
      {{ form.as_p}}
      <input type="submit" value="Create">
    </form>
  
  <p><a id="admin" href="{% url 'flightsapp:new-departure' %}">New Departure</a></p>
  <p><a class="home" href="{% url 'flightsapp:home' %}">Flights</a></p>
</body>
</html>

flights/flightsapp/templates/flightsapp/new-departure.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<link rel="stylesheet" href="{% static 'flightsapp/generic.css'%}">

<body>
  <form class="new" method="post">
    <h1>New Departure</h1>
      {% csrf_token %}
      {{ form.as_p}}
      <input type="submit" value="Crear">
    </form>
  
  <p><a id="admin" href="{% url 'flightsapp:new-arrival' %}">New Arrival</a></p>
  <p><a class="home" href="{% url 'flightsapp:home' %}">Flights</a></p>

</body>
</html>